import test from "node:test";
import assert from "node:assert/strict";
import { createProfileStore, validProfile } from "../state";
import { createMockProfileService } from "../mock";
const setup = async (scenario: Parameters<typeof createMockProfileService>[0] = "success") => { const service = createMockProfileService(scenario, 0); const store = createProfileStore(service); store.setActive(true); await store.load(); return { service, store }; };
test("load success and Unicode validation boundaries", async () => { const {store} = await setup(); const v=store.getState().draft; assert.ok(validProfile({...v,nickname:"😀".repeat(10),bio:"가".repeat(50)})); assert.equal(validProfile({...v,nickname:"😀".repeat(11)}),false); assert.equal(validProfile({...v,bio:"가".repeat(51)}),false); });
test("known save failure preserves input and saved value; explicit Retry commits once", async () => { const {store,service}=await setup("save-error"); const before=service.getSaved(); store.edit({...store.getState().draft,nickname:"변경"}); await store.save(); assert.deepEqual(service.getSaved(),before); assert.equal(store.getState().draft.nickname,"변경"); await store.save(); assert.equal(service.getSaved()?.nickname,"변경"); });
test("cancel discards edits while saved profile stays unchanged",async()=>{const {store,service}=await setup();const before=service.getSaved();store.edit({...store.getState().draft,nickname:"변경"});store.cancel();assert.deepEqual(store.getState().draft,before);assert.deepEqual(service.getSaved(),before);});
test("location candidates do not auto select or grant qualifications",async()=>{const {store}=await setup();const before=structuredClone(store.getState().draft);await store.locate();assert.equal(store.getState().candidate,null);assert.deepEqual(store.getState().draft,before);store.choose(store.getState().candidates[1]);store.applyCandidate();assert.equal(store.getState().draft.activityRegion?.reference,"preview-wolgye2");assert.equal("capabilities" in store.getState().draft,false);});
test("nested region cancellation restores prior region and preserves profile input",async()=>{const {store}=await setup();store.edit({...store.getState().draft,nickname:"입력"});store.setOrigin("profile");await store.locate();store.choose(store.getState().candidates[1]);store.applyCandidate();store.cancelRegion();assert.equal(store.getState().draft.nickname,"입력");assert.equal(store.getState().draft.activityRegion?.reference,"preview-wolgye1");});
test("location refusal falls back to manual search",async()=>{const {store}=await setup("denied");await store.locate();assert.equal(store.getState().candidatePhase,"denied");store.setQuery("월계2");await store.search();assert.equal(store.getState().candidates.length,1);assert.equal(store.getState().candidate,null);});
for(const [scenario,phase] of [["location-error","error"],["no-candidates","empty"],["search-error","error"]] as const)test(scenario,async()=>{const {store}=await setup(scenario);if(scenario==="search-error")await store.search();else await store.locate();assert.equal(store.getState().candidatePhase,phase);});
test("load Retry and Empty are separate states",async()=>{const {store}=await setup("load-error");assert.equal(store.getState().phase,"error");await store.load();assert.equal(store.getState().phase,"editing");assert.equal((await setup("empty")).store.getState().phase,"empty");});
test("nickname collision and denied write never replace saved profile",async()=>{for(const scenario of ["nickname","forbidden"] as const){const {store,service}=await setup(scenario);const saved=service.getSaved();store.edit({...store.getState().draft,nickname:"중복"});await store.save();assert.equal(store.getState().failure?.reason,scenario);assert.deepEqual(service.getSaved(),saved);}});
test("unknown save result prevents duplicate Retry until reconciliation",async()=>{const {store}=await setup("unknown");await store.save();assert.equal(store.getState().failure?.retryable,false);store.edit({...store.getState().draft,nickname:"수정"});assert.equal(store.getState().failure?.reason,"unknown");await store.save();assert.equal(store.getState().phase,"editing");});
test("guest operations and stale load completion cannot expose saved data",async()=>{const service=createMockProfileService("success",20);const store=createProfileStore(service);await store.load();assert.equal(store.getState().phase,"idle");store.setActive(true);const pending=store.load();store.setActive(false);await pending;assert.equal(store.getState().saved,null);});
test("pending duplicate saves and cancellation preserve known saved value",async()=>{const service=createMockProfileService("success",20);const store=createProfileStore(service);store.setActive(true);await store.load();const before=service.getSaved();store.edit({...store.getState().draft,nickname:"변경"});const pending=store.save();await store.save();store.cancel();await pending;assert.deepEqual(service.getSaved(),before);assert.equal(store.getState().failure?.reason,"unknown");});

test("photo removal and replacement are separate client draft intents",async()=>{const {store,service}=await setup();store.edit({...store.getState().draft,photo:{kind:"remove"}});await store.save();assert.equal(service.getSaved()?.photoUrl,undefined);const file=new File(["fixture"],"preview.png",{type:"image/png"});store.edit({...store.getState().draft,photo:{kind:"replace",file}});await store.save();const photo=service.getSaved()?.photo;assert.equal(photo?.kind,"replace");if(photo?.kind==="replace")assert.equal(await photo.file.text(),"fixture");});
test("scrolls and query are preserved independently; clear prevents account carryover",async()=>{const {store}=await setup();store.setScroll("profile",140);store.setScroll("region",250);store.setQuery("월계");store.cancelRegion();assert.deepEqual(store.getState().scroll,{profile:140,region:250});assert.equal(store.getState().query,"월계");store.clear();assert.equal(store.getState().saved,null);assert.equal(store.getState().query,"");});

test("effect cleanup during initial load permits remount Retry instead of stuck loading",async()=>{const store=createProfileStore(createMockProfileService("success",15));store.setActive(true);const first=store.load();store.dispose();assert.equal(store.getState().phase,"idle");await store.load();await first;assert.equal(store.getState().phase,"editing");});
