"use client";
import { useEffect, useState } from "react";
import { Button } from "../../components/ui/Button";
import { Notice } from "../../components/ui/Notice";
import { reactionLabels, reactionTypes, type ReactionSnapshot, type ReactionState, type ReactionType } from "./model";
import type { ReactionService } from "./service";

export function ReactionControls({ postId, service, canReact, onInvalidate }: { postId: string; service: ReactionService; canReact: boolean; onInvalidate?: (postId: string) => void }) {
  const [state, setState] = useState<ReactionState>({ kind: "loading" }); const [pending, setPending] = useState<ReactionType[]>([]); const [failed, setFailed] = useState<{ type: ReactionType; selected: boolean } | null>(null); const [message, setMessage] = useState(""); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; void service.get(postId).then((value) => { if (active) setState({ kind: "ready", snapshot: value }); }).catch((error: unknown) => { if (active) setState({ kind: "error", message: error instanceof Error ? error.message : "반응을 불러오지 못했습니다." }); }); return () => { active = false; }; }, [attempt, postId, service]);
  const toggle = async (type: ReactionType, forced?: boolean) => { if (state.kind !== "ready" || pending.includes(type) || !canReact) return; const selected = forced ?? !state.snapshot.selected.includes(type); const before = state.snapshot; const chosen = new Set(before.selected); if (selected) chosen.add(type); else chosen.delete(type); const optimistic: ReactionSnapshot = { counts: { ...before.counts, [type]: Math.max(0, before.counts[type] + (selected ? 1 : -1)) }, selected: [...chosen], total: Math.max(0, before.total + (selected ? 1 : -1)) }; setState({ kind: "ready", snapshot: optimistic }); setPending((items) => [...items, type]); setFailed(null); try { setState({ kind: "ready", snapshot: await service.set(postId, type, selected) }); setMessage(selected ? `${reactionLabels[type]}를 남겼습니다.` : `${reactionLabels[type]}를 취소했습니다.`); onInvalidate?.(postId); } catch (error) { setState({ kind: "ready", snapshot: before }); setFailed({ type, selected }); setMessage(error instanceof Error ? error.message : "반응 처리에 실패했습니다."); } finally { setPending((items) => items.filter((item) => item !== type)); } };
  if (!canReact) return <Notice tone="info">현재 권한으로는 반응을 남길 수 없습니다.</Notice>;
  if (state.kind === "loading") return <Notice aria-busy="true">반응을 불러오는 중입니다.</Notice>;
  if (state.kind === "error") return <><Notice tone="error">{state.message}</Notice><Button className="mt-2" onClick={() => { setState({ kind: "loading" }); setAttempt((current) => current + 1); }}>반응 다시 시도</Button></>;
  return <section aria-label="게시물 반응"><p className="text-caption text-secondary">반응 {state.snapshot.total}</p><div className="mt-2 flex flex-wrap gap-2">{reactionTypes.map((type) => { const selected = state.snapshot.selected.includes(type); return <Button key={type} variant={selected ? "primary" : "secondary"} disabled={pending.includes(type)} onClick={() => void toggle(type)}>{pending.includes(type) ? "처리 중" : `${reactionLabels[type]} ${state.snapshot.counts[type]}`}</Button>; })}</div>{message && <Notice tone={failed ? "error" : "info"} className="mt-2">{message}{failed && <Button variant="secondary" className="ml-2 min-h-0 px-2 py-1" onClick={() => void toggle(failed.type, failed.selected)}>다시 시도</Button>}</Notice>}</section>;
}
