import type { ActivityStatus, PostDisplayModel, PostType } from "../post/model";

export type PhotoSelection = { id: string; fileId?: string; photoId?: string; file?: File; name: string; type: string; size: number; previewUrl?: string; status: "selected" | "pending" | "success" | "error" | "ready" };
export type PostFormState = { type: PostType; regionId: string; topic: string; title: string; content: string; photos: readonly PhotoSelection[]; referenceLink: string; anonymous: boolean; activity?: { source: string; schedule: string; location: string; status: ActivityStatus; link: string }; vote?: { question: string; options: readonly string[]; endsAt: string; status: "OPEN" | "ENDED" } };
export type EditorResult = { postId: string; post?: import("../post/model").PostDisplayModel };
export const maxPhotoCount = 10;
export const maxPhotoBytes = 10_000_000;

export function emptyPostForm(type: PostType = "LOCAL_AGENDA"): PostFormState {
  return { type, regionId: "", topic: "환경", title: "", content: "", photos: [], referenceLink: "", anonymous: false, ...(type === "LOCAL_ACTIVITY" ? { activity: { source: "", schedule: "", location: "", status: "UPCOMING", link: "" } } : {}), ...(type === "VOTE" ? { vote: { question: "", options: ["", ""], endsAt: "", status: "OPEN" } } : {}) };
}
export function canUseAnonymous(form: PostFormState, isInstitution = false) { return form.type === "LOCAL_AGENDA" && !isInstitution; }
export function photoError(photos: readonly PhotoSelection[]) { if (photos.length > maxPhotoCount) return "You can attach up to 10 photos."; if (photos.some((photo) => !["image/jpeg", "image/png"].includes(photo.type))) return "Only JPG and PNG photos are supported."; if (photos.reduce((sum, photo) => sum + photo.size, 0) > maxPhotoBytes) return "Photos must total 10MB or less."; return undefined; }
export function formErrors(form: PostFormState) { const errors: string[] = []; if (!form.regionId || !form.topic || !form.title.trim() || !form.content.trim()) errors.push("Complete the required common fields."); if (form.type === "LOCAL_ACTIVITY" && (!form.activity?.source.trim() || !form.activity.schedule || !form.activity.location.trim() || !form.activity.status)) errors.push("Complete the activity fields."); if (form.type === "VOTE" && (!form.vote?.question.trim() || !form.vote.endsAt || form.vote.options.length < 2 || form.vote.options.length > 10 || form.vote.options.some((option) => !option.trim()))) errors.push("A vote needs a question, end time, and 2 to 10 options."); const photo = photoError(form.photos); if (photo) errors.push(photo); return errors; }
export function formFromPost(post: PostDisplayModel): PostFormState { return { ...emptyPostForm(post.type), type: post.type, regionId: post.metadata.regionId ?? "", topic: post.metadata.topic, title: post.title, content: post.content, photos: post.images.map((image) => ({ id: image.id, name: image.alt, type: "image/jpeg", size: 0, previewUrl: image.url, status: "ready" })), referenceLink: post.referenceLink?.href ?? "", anonymous: post.anonymous, ...(post.type === "LOCAL_ACTIVITY" ? { activity: { source: post.activity.source, schedule: post.activity.scheduleLabel, location: post.activity.location, status: post.activity.status, link: post.activity.participationLink?.href ?? "" } } : {}), ...(post.type === "VOTE" ? { vote: { question: post.content, options: ["", ""], endsAt: "", status: post.vote.status } } : {}) }; }
