"use client";
/* eslint-disable @next/next/no-img-element -- local previews are not Next image sources. */
import { useState } from "react";
import { Header } from "../../components/layout/Header";
import { MobileLayout } from "../../components/layout/MobileLayout";
import { Button } from "../../components/ui/Button";
import { Input } from "../../components/ui/Input";
import { Notice } from "../../components/ui/Notice";
import { TextArea } from "../../components/ui/TextArea";
import { useNavigation } from "../../lib/navigation";
import { canUseAnonymous, emptyPostForm, formErrors, maxPhotoCount, type PhotoSelection, type PostFormState } from "./model";
import type { PhotoService, PostEditorService } from "./service";

type Props = { mode: "create" | "edit"; postId?: string; initial?: PostFormState; service?: PostEditorService; photoService?: PhotoService; canEdit?: boolean; isInstitution?: boolean; onCancel?: () => void; onInvalidate?: (postId: string) => void };
const types = ["LOCAL_AGENDA", "LOCAL_ACTIVITY", "VOTE"] as const;
const typeLabels: Record<(typeof types)[number], string> = { LOCAL_AGENDA: "지역 안건", LOCAL_ACTIVITY: "지역 활동 정보", VOTE: "투표" };
export function PostEditorScreen({ mode, postId, initial, service, photoService, canEdit = true, isInstitution = false, onCancel, onInvalidate }: Props) {
 const navigation = useNavigation(); const [form,setForm]=useState<PostFormState>(initial ?? emptyPostForm()); const [error,setError]=useState(""); const [pending,setPending]=useState(false); const [confirmDelete,setConfirmDelete]=useState(false);
 const change=(next:Partial<PostFormState>)=>setForm(current=>({...current,...next})); const chooseType=(type:typeof types[number])=>setForm(emptyPostForm(type)); const updatePhoto=(id:string,next:Partial<PhotoSelection>)=>setForm(current=>({...current,photos:current.photos.map(photo=>photo.id===id?{...photo,...next}:photo)}));
 const processPhoto=async(photo:PhotoSelection)=>{if(!photoService)return;updatePhoto(photo.id,{status:"pending"});try{await photoService.process(photo);updatePhoto(photo.id,{status:"success"});}catch{updatePhoto(photo.id,{status:"error"});}};
 const addPhotos=(files:FileList|null)=>{ if(!files)return; const next=[...form.photos,...Array.from(files).map((file,index):PhotoSelection=>({id:`local-${Date.now()}-${index}`,file,name:file.name,type:file.type,size:file.size,previewUrl:URL.createObjectURL(file),status:"selected"}))]; change({photos:next}); next.slice(form.photos.length).forEach(photo=>void processPhoto(photo)); };
 const submit=async()=>{ const issues=formErrors(form); if(issues.length){setError(issues.join(" "));return;} if(!service){setError("The real post API is not connected yet.");return;} setPending(true);setError("");try{const result=mode==="create"?await service.create(form):await service.update(postId!,form); navigation.navigate({destination:{id:"post",params:{postId:result.postId}},origin:{id:mode==="create"?"newPost":"editPost",params:{postId:result.postId}}});}catch{setError("The post could not be saved. Your form is still available to retry.");}finally{setPending(false);}};
 const remove=async()=>{if(!service||!postId)return;setPending(true);try{await service.remove(postId);onInvalidate?.(postId);const origin=navigation.state.current?.origin;if(origin)navigation.navigate({destination:origin},true);else navigation.back();}catch{setError("The post could not be deleted. Please retry.");}finally{setPending(false);}};
 const voteLocked=mode==="edit"&&form.type==="VOTE"&&form.vote?.status==="OPEN"; const voteEnded=mode==="edit"&&form.type==="VOTE"&&form.vote?.status==="ENDED";
 if(mode==="edit"&&!canEdit)return <MobileLayout header={<Header title="게시물 수정" onBack={onCancel}/> }><Notice tone="error">이 게시물을 수정할 권한이 없습니다.</Notice></MobileLayout>;
 return <MobileLayout header={<Header title={mode==="create"?"글쓰기":"게시물 수정"} onBack={onCancel}/>}><section className="flex flex-col gap-4"><label className="flex flex-col gap-1 text-body">유형<select value={form.type} disabled={mode==="edit"||pending} onChange={e=>chooseType(e.currentTarget.value as typeof form.type)} className="w-full rounded-input border border-border p-3">{types.map(type=><option key={type} value={type}>{typeLabels[type]}</option>)}</select></label><Input label="제목" value={form.title} onChange={e=>change({title:e.currentTarget.value})} placeholder="제목을 입력하세요"/><TextArea label="내용" value={form.content} onChange={e=>change({content:e.currentTarget.value})} placeholder="내용을 입력하세요"/><Input label="참고 링크" value={form.referenceLink} onChange={e=>change({referenceLink:e.currentTarget.value})} placeholder="선택 입력"/>
 {canUseAnonymous(form,isInstitution)&&<label className="text-body"><input type="checkbox" checked={form.anonymous} onChange={e=>change({anonymous:e.currentTarget.checked})}/> 익명으로 게시하기</label>}
 {form.type==="LOCAL_ACTIVITY"&&<><Input label="출처" value={form.activity?.source??""} onChange={e=>change({activity:{...form.activity!,source:e.currentTarget.value}})} placeholder="출처"/><Input label="일정" value={form.activity?.schedule??""} onChange={e=>change({activity:{...form.activity!,schedule:e.currentTarget.value}})} placeholder="일정"/><Input label="장소" value={form.activity?.location??""} onChange={e=>change({activity:{...form.activity!,location:e.currentTarget.value}})} placeholder="장소"/></>}
 {form.type==="VOTE"&&<><Input label="투표 질문" disabled={voteLocked||voteEnded} value={form.vote?.question??""} onChange={e=>change({vote:{...form.vote!,question:e.currentTarget.value}})} placeholder="투표 질문"/>{form.vote?.options.map((option,index)=><Input label={`선택지 ${index+1}`} key={index} disabled={voteLocked||voteEnded} value={option} onChange={e=>change({vote:{...form.vote!,options:form.vote!.options.map((value,i)=>i===index?e.currentTarget.value:value)}})} placeholder={`선택지 ${index+1}`}/>) } {!voteLocked&&!voteEnded&&form.vote&&form.vote.options.length<10&&<Button variant="secondary" onClick={()=>change({vote:{...form.vote!,options:[...form.vote!.options,""]}})}>선택지 추가</Button>}{voteEnded&&<Notice tone="warning">종료된 투표는 수정하거나 삭제할 수 없습니다.</Notice>}</>}
 <label className="block">사진 (JPG/PNG, 최대 {maxPhotoCount}장, 총 10MB)<input className="mt-2 block" type="file" accept="image/jpeg,image/png" multiple onChange={e=>addPhotos(e.currentTarget.files)}/></label><div className="flex flex-wrap gap-2">{form.photos.map((photo,index)=><div key={photo.id} className="rounded border border-border p-2 text-caption">{photo.previewUrl&&<img src={photo.previewUrl} alt="" className="h-16 w-16 object-cover"/>}<p>{index+1}. {photo.name}</p><div className="mt-1 flex gap-2"><button type="button" disabled={index===0} onClick={()=>change({photos:form.photos.map((item,i)=>i===index-1?photo:i===index?form.photos[index-1]:item)})}>앞으로</button><button type="button" disabled={index===form.photos.length-1} onClick={()=>change({photos:form.photos.map((item,i)=>i===index+1?photo:i===index?form.photos[index+1]:item)})}>뒤로</button><button type="button" onClick={()=>change({photos:form.photos.filter(item=>item.id!==photo.id)})}>삭제</button></div></div>)}</div>
 {error&&<Notice tone="error" role="alert">{error}</Notice>}<Button disabled={pending||voteEnded} onClick={()=>void submit()}>{pending?"저장 중…":mode==="create"?"게시하기":"수정 저장"}</Button>{mode==="edit"&&!voteEnded&&<Button variant="secondary" disabled={pending} onClick={()=>setConfirmDelete(true)}>삭제</Button>}{confirmDelete&&<Notice tone="warning"><p>이 게시물을 삭제할까요?</p><Button className="mt-2" disabled={pending} onClick={()=>void remove()}>삭제 확인</Button><Button className="mt-2 ml-2" variant="secondary" onClick={()=>setConfirmDelete(false)}>취소</Button></Notice>}</section></MobileLayout>;
}
