"use client";
import { useState } from "react";
import { Header } from "../../components/layout/Header";
import { MobileLayout } from "../../components/layout/MobileLayout";
import { Button } from "../../components/ui/Button";
import { Input } from "../../components/ui/Input";
import { Notice } from "../../components/ui/Notice";
import { TextArea } from "../../components/ui/TextArea";
import { useNavigation } from "../../lib/navigation";
import { emptyPostForm, formErrors, type PostFormState } from "./model";
import type { DraftService } from "./draft";
import type { PhotoService, PostEditorService } from "./service";

type Props={mode:"create"|"edit";postId?:string;initial?:PostFormState;service?:PostEditorService;draftService?:DraftService;photoService?:PhotoService;canEdit?:boolean;onCancel?:()=>void;onInvalidate?:(id:string)=>void};
export function PostEditorScreen({mode,postId,initial,service,draftService,canEdit=true,onCancel,onInvalidate}:Props){const nav=useNavigation();const [form,setForm]=useState(initial??emptyPostForm());const [draft,setDraft]=useState<"idle"|"pending"|"success"|"error">("idle");const [error,setError]=useState("");const change=(next:Partial<PostFormState>)=>setForm(current=>({...current,...next}));const saveDraft=async()=>{if(!draftService)return;setDraft("pending");try{await draftService.save(form);setDraft("success");}catch{setDraft("error");}};const submit=async()=>{const issues=formErrors(form);if(issues.length){setError(issues.join(" "));return}if(!service){setError("실제 게시 API가 연결되지 않았습니다.");return}const result=mode==="create"?await service.create(form):await service.update(postId!,form);nav.navigate({destination:{id:"post",params:{postId:result.postId}},origin:{id:mode==="create"?"newPost":"editPost",params:{postId:result.postId}}})};const remove=async()=>{if(!service||!postId)return;await service.remove(postId);onInvalidate?.(postId);const origin=nav.state.current?.origin;if(origin)nav.navigate({destination:origin},true);else nav.back()};if(mode==="edit"&&!canEdit)return <MobileLayout header={<Header title="게시물 수정" onBack={onCancel}/>}><Notice tone="error">수정 권한이 없습니다.</Notice></MobileLayout>;return <MobileLayout header={<Header title={mode==="create"?"글쓰기":"게시물 수정"} onBack={onCancel}/>}><section className="flex flex-col gap-4"><Input label="제목" value={form.title} onChange={e=>change({title:e.currentTarget.value})}/><TextArea label="내용" value={form.content} onChange={e=>change({content:e.currentTarget.value})}/><Input label="참고 링크" value={form.referenceLink} onChange={e=>change({referenceLink:e.currentTarget.value})}/>{draft==="success"&&<Notice>임시저장되었습니다. 공개 게시되지 않았습니다.</Notice>}{draft==="error"&&<Notice tone="error">임시저장에 실패했습니다. 입력은 유지됩니다.</Notice>}<Button variant="secondary" disabled={draft==="pending"||!draftService} onClick={()=>void saveDraft()}>{draft==="pending"?"임시저장 중…":draft==="error"?"임시저장 재시도":"임시저장"}</Button><Button onClick={()=>void submit()}>게시하기</Button>{mode==="edit"&&<Button variant="secondary" onClick={()=>void remove()}>삭제</Button>}{error&&<Notice tone="error">{error}</Notice>}</section></MobileLayout>}
